/** @format */

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { NextPage } from 'next'
import Home from '../src/screen/home/Home'
import { useAppSelector } from '../src/hooks/useReduxHooks'
import { useActions } from '../src/hooks/useActions'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useTranslation } from 'react-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { checkAuth } from '../src/state/slice/auth-slice/auth.actions'

const inter = Inter({ subsets: ['latin'] })

// import { useEffect } from 'react'
// import { useRouter } from 'next/router'
// import { useAppSelector } from '../src/hooks/useReduxHooks'
// import { useActions } from '../src/hooks/useActions'

const HomePage: NextPage<any> = () => {
  const { isAuth } = useAppSelector((state) => state.authSlice)
  const actions = useActions()
  const router = useRouter()

  useEffect(() => {
    // Dispatch the action to check if the user is authenticated
    actions.checkAuth()

    // Depending on the authentication status, redirect the user
    if (isAuth) {
      router.push('/dashboard')
    } else {
      router.push('/sign-in')
    }

    // Add `isAuth` to the dependency array so this effect runs when `isAuth` changes
  }, [isAuth, actions, router])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div style={{ overflow: 'hidden' }}>
          <Home />
        </div>
      </main>
    </>
  )
}

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
        'dashboard',
        'myCourses',
      ])),
    },
  }
}

export default HomePage
